name: open_yapper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  material_symbols_icons: ^4.2906.0
  shared_preferences: ^2.2.2
  record: ^6.0.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.0
  http: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true  # App Store requires no alpha channel
  macos:
    generate: true
  web:
    generate: true
    background_color: "#F4BA83"
    theme_color: "#F4BA83"
  windows:
    generate: true

flutter:
  uses-material-design: true
  fonts:
    - family: Haskoy
      fonts:
        - asset: assets/font/Haskoy-variable.ttf
